window.POLE_INVENTORY = [
  {
    id: "zontes-368k-2026",
    brand: "Zontes",
    model: "368K",
    family: "Maxiscooter",
    condition: "ocasion",
    conditionLabel: "Ocasión · 2026",
    category: ["urbana", "scooter", "a2"],
    price: 4490,
    year: 2026,
    km: 2700,
    image: "assets/motos/inventario/zontes-368k.webp",
    alt: "Zontes 368K blanca expuesta en Pole Position",
    theme: "card-zontes",
    status: "available",
    description: "Maxiscooter tecnológico y cómodo para ciudad y carretera, con una unidad de ocasión de kilometraje contenido.",
    specs: { "Cilindrada": "368 cc", "Kilometraje": "2.700 km", "Año": "2026", "Carné": "A2" }
  },
  {
    id: "royal-enfield-hunter-350",
    brand: "Royal Enfield",
    model: "Hunter 350",
    family: "Roadster urbana",
    condition: "nueva",
    conditionLabel: "Gama nueva",
    category: ["urbana", "clasica", "a2"],
    price: null,
    year: 2026,
    km: 0,
    image: "assets/motos/inventario/royal-enfield-hunter-350.webp",
    alt: "Royal Enfield Hunter 350 Dapper White en vista lateral",
    theme: "card-red",
    status: "on_request",
    description: "Una roadster ligera, accesible y con personalidad clásica. Ideal para iniciarse con el carné A2.",
    specs: { "Cilindrada": "349 cc", "Potencia": "20,2 CV", "Carné": "A2", "Uso": "Ciudad y carretera" }
  },
  {
    id: "suzuki-vstrom-1050de-2024",
    brand: "Suzuki",
    model: "V-Strom 1050DE",
    family: "Trail adventure",
    condition: "km0",
    conditionLabel: "KM0 · 2024",
    category: ["trail", "adventure"],
    price: 13250,
    year: 2024,
    km: 0,
    image: "assets/motos/inventario/suzuki-vstrom-1050de.webp",
    alt: "Suzuki V-Strom 1050DE azul y blanca en la exposición",
    theme: "card-sand",
    status: "available",
    description: "Trail de gran cilindrada orientada a largos viajes y escapadas fuera del asfalto. Unidad matriculada con cero kilómetros.",
    specs: { "Cilindrada": "1.037 cc", "Kilometraje": "0 km", "Año": "2024", "Categoría": "Trail" }
  },
  {
    id: "super-soco-f01",
    brand: "Super Soco",
    model: "F01",
    family: "Movilidad urbana",
    condition: "nueva",
    conditionLabel: "100% eléctrica",
    category: ["electrica", "urbana"],
    price: 3000,
    year: 2026,
    km: 0,
    image: "assets/motos/inventario/super-soco-f01.webp",
    alt: "Super Soco F01 eléctrica roja fotografiada en Pole Position",
    theme: "card-electric",
    status: "available",
    description: "Movilidad eléctrica silenciosa y práctica para desplazamientos urbanos, con batería extraíble y recarga doméstica.",
    specs: { "Autonomía": "Hasta 80 km", "Carga": "Aprox. 3,5 h", "Motor": "Eléctrico", "Uso": "Urbano" }
  },
  {
    id: "peugeot-xp400",
    brand: "Peugeot",
    model: "XP400",
    family: "Scooter premium",
    condition: "nueva",
    conditionLabel: "Gama nueva",
    category: ["urbana", "scooter", "a2"],
    price: null,
    year: 2026,
    km: 0,
    image: "assets/motos/inventario/peugeot-xp400.webp",
    alt: "Peugeot XP400 blanco en carretera",
    theme: "card-blue",
    status: "on_request",
    description: "Scooter crossover de acabado premium, pensado para ofrecer confort diario y capacidad fuera de la ciudad.",
    specs: { "Cilindrada": "400 cc", "Carné": "A2", "Categoría": "Crossover", "Uso": "Mixto" }
  },
  {
    id: "suzuki-burgman-650-2018",
    brand: "Suzuki",
    model: "Burgman 650",
    family: "Gran turismo scooter",
    condition: "ocasion",
    conditionLabel: "Ocasión · 2018",
    category: ["urbana", "scooter"],
    price: 5250,
    year: 2018,
    km: 77000,
    image: "assets/motos/inventario/suzuki-burgman-650.webp",
    alt: "Suzuki Burgman 650 blanca de ocasión en la exposición",
    theme: "card-white",
    status: "available",
    description: "Maxiscooter Gran Turismo con excelente protección aerodinámica, confort para dos y gran capacidad de carga.",
    specs: { "Cilindrada": "638 cc", "Kilometraje": "77.000 km", "Año": "2018", "Categoría": "Maxiscooter" }
  },
  {
    id: "kawasaki-z900-2020",
    brand: "Kawasaki",
    model: "Z900",
    family: "Naked deportiva",
    condition: "ocasion",
    conditionLabel: "Ocasión · 2020",
    category: ["urbana", "naked", "deportiva"],
    price: 6450,
    year: 2020,
    km: 20600,
    image: "assets/motos/inventario/kawasaki-z900.webp",
    alt: "Kawasaki Z900 de ocasión fotografiada en Pole Position",
    theme: "card-green",
    status: "available",
    description: "Naked de cuatro cilindros con respuesta deportiva, electrónica actual y una conducción muy directa.",
    specs: { "Potencia": "125 CV", "Kilometraje": "20.600 km", "Año": "2020", "Categoría": "Naked" }
  }
];
